services:
  nginx:
    image: "server"
    build: nginx/
    ports:
      - "127.0.0.1:443:443"
    extra_hosts:
      - "dtome-pe.42.fr:127.0.0.1"
    volumes:
      - /home/dtome-pe/data/web:/home/dtome-pe/data/web

  #wordpress: 
   # image: "web"
    #build: wordpress/
    #volumes:
     #- /home/dtome-pe/data/web:/home/dtome-pe/data/web

  mariadb:
    build: mariadb/
    volumes: 
    - /home/dtome-pe/data/db:/home/dtome-pe/data/db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    