services:
  
  nginx:
    image: server
    container_name: nginx
    build: nginx/
    ports:
      - "127.0.0.1:443:443"
      - "9000"
    extra_hosts:
      - "dtome-pe.42.fr:127.0.0.1"
    volumes:
      - web_vol:/var/www/wordpress
    networks:
      - inception
    restart: always
  mariadb:
    image: db
    container_name: mariadb
    build: mariadb/
    ports:
      - "3306"
    volumes: 
    - db_vol:/var/lib/mysql/
    env_file: .env
    networks:
      - inception
    restart: always

  wordpress:
    depends_on:
        - mariadb
    image: web
    container_name: wordpress
    build: wordpress/
    env_file: .env
    ports:
      - "9000"
      - "3306"
    extra_hosts:
      - "wordpress.srcs_inception:127.0.0.1"
    volumes:
     - web_vol:/var/www/wordpress
    networks:
      - inception
    restart: always

volumes:
  web_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dtome-pe/data/web
  db_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dtome-pe/data/db

networks:
  inception:
    driver: bridge
  
    